import type {
  Appointment,
  InventoryItem,
  Patient,
  Payment,
  ProcedureCatalogItem,
  ClinicMember,
  TreatmentPlan,
} from "./types";

export const patients: Patient[] = [
  {
    id: "p1",
    patientNo: "PT-2048",
    name: "Sophia Martinez",
    initials: "SM",
    age: 34,
    gender: "Female",
    phone: "+1 (415) 555-0138",
    email: "sophia.martinez@example.com",
    lastVisit: "Aug 24, 2026",
    nextVisit: "Sep 03, 2026",
    status: "Active",
    allergies: ["Penicillin"],
    conditions: ["Mild hypertension"],
    notes:
      "Prefers morning appointments. Anxious about local anaesthesia; explain each step before treatment.",
    balance: 420,
    avatarColor: "bg-rose-100 text-rose-700",
    toothChart: {
      3: "Crown",
      8: "Filling",
      12: "Caries",
      19: "Root Canal",
      30: "Missing",
    },
  },
  {
    id: "p2",
    patientNo: "PT-2047",
    name: "Marcus Chen",
    initials: "MC",
    age: 41,
    gender: "Male",
    phone: "+1 (415) 555-0172",
    email: "marcus.chen@example.com",
    lastVisit: "Aug 23, 2026",
    nextVisit: "Aug 28, 2026",
    status: "Active",
    allergies: [],
    conditions: ["Type 2 diabetes"],
    notes: "Monitor healing closely after surgical procedures.",
    balance: 0,
    avatarColor: "bg-blue-100 text-blue-700",
    toothChart: { 2: "Filling", 14: "Caries", 15: "Caries", 29: "Implant" },
  },
  {
    id: "p3",
    patientNo: "PT-2046",
    name: "Emma Thompson",
    initials: "ET",
    age: 29,
    gender: "Female",
    phone: "+1 (415) 555-0155",
    email: "emma.thompson@example.com",
    lastVisit: "Aug 21, 2026",
    nextVisit: "Sep 12, 2026",
    status: "Active",
    allergies: ["Latex"],
    conditions: [],
    notes: "Clear aligner patient. Progress photos every 8 weeks.",
    balance: 1250,
    avatarColor: "bg-violet-100 text-violet-700",
    toothChart: { 5: "Filling", 18: "Caries", 31: "Crown" },
  },
  {
    id: "p4",
    patientNo: "PT-2045",
    name: "Noah Williams",
    initials: "NW",
    age: 52,
    gender: "Male",
    phone: "+1 (415) 555-0119",
    email: "noah.williams@example.com",
    lastVisit: "Aug 18, 2026",
    status: "Active",
    allergies: ["Ibuprofen"],
    conditions: ["Blood thinner", "High blood pressure"],
    notes: "Cardiology clearance required for surgical treatments.",
    balance: 780,
    avatarColor: "bg-amber-100 text-amber-700",
    toothChart: {
      4: "Extraction",
      13: "Crown",
      20: "Missing",
      21: "Missing",
      28: "Root Canal",
    },
  },
  {
    id: "p5",
    patientNo: "PT-2044",
    name: "Olivia Brown",
    initials: "OB",
    age: 23,
    gender: "Female",
    phone: "+1 (415) 555-0186",
    email: "olivia.brown@example.com",
    lastVisit: "Aug 16, 2026",
    nextVisit: "Oct 02, 2026",
    status: "Active",
    allergies: [],
    conditions: [],
    notes: "Routine recall patient.",
    balance: 0,
    avatarColor: "bg-emerald-100 text-emerald-700",
    toothChart: { 1: "Healthy", 16: "Filling", 17: "Filling", 32: "Healthy" },
  },
  {
    id: "p6",
    patientNo: "PT-2043",
    name: "Liam Davis",
    initials: "LD",
    age: 67,
    gender: "Male",
    phone: "+1 (415) 555-0143",
    email: "liam.davis@example.com",
    lastVisit: "Jul 29, 2026",
    status: "Inactive",
    allergies: ["Sulfa drugs"],
    conditions: ["Pacemaker"],
    notes: "Implant maintenance every four months.",
    balance: 310,
    avatarColor: "bg-cyan-100 text-cyan-700",
    toothChart: {
      6: "Implant",
      7: "Implant",
      10: "Crown",
      22: "Missing",
      23: "Implant",
    },
  },
];

export const appointments: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    patientName: "Sophia Martinez",
    time: "8:30 AM",
    endTime: "9:15 AM",
    date: "2026-08-27",
    treatment: "Crown preparation",
    treatmentPrice: 950,
    doctor: "Dr. Maya Chen",
    providerId: "demo-doctor-1",
    room: "Room 2",
    status: "Checked in",
    color: "#0f9f8f",
  },
  {
    id: "a2",
    patientId: "p2",
    patientName: "Marcus Chen",
    time: "9:30 AM",
    endTime: "10:15 AM",
    date: "2026-08-27",
    treatment: "Root canal · Session 2",
    treatmentPrice: 850,
    doctor: "Dr. James Wilson",
    providerId: "demo-doctor-2",
    room: "Room 1",
    status: "In treatment",
    color: "#6d5dfc",
  },
  {
    id: "a3",
    patientId: "p5",
    patientName: "Olivia Brown",
    time: "10:30 AM",
    endTime: "11:00 AM",
    date: "2026-08-27",
    treatment: "Cleaning & exam",
    treatmentPrice: 240,
    doctor: "Dr. Maya Chen",
    providerId: "demo-doctor-1",
    room: "Room 3",
    status: "Confirmed",
    color: "#f59e0b",
  },
  {
    id: "a4",
    patientId: "p3",
    patientName: "Emma Thompson",
    time: "11:30 AM",
    endTime: "12:15 PM",
    date: "2026-08-27",
    treatment: "Aligner progress check",
    treatmentPrice: 320,
    doctor: "Dr. Maya Chen",
    providerId: "demo-doctor-1",
    room: "Room 2",
    status: "Confirmed",
    color: "#0ea5e9",
  },
  {
    id: "a5",
    patientId: "p4",
    patientName: "Noah Williams",
    time: "1:30 PM",
    endTime: "2:30 PM",
    date: "2026-08-27",
    treatment: "Surgical consultation",
    treatmentPrice: 260,
    doctor: "Dr. James Wilson",
    providerId: "demo-doctor-2",
    room: "Room 1",
    status: "Pending",
    color: "#e55f7c",
  },
  {
    id: "a6",
    patientId: "p6",
    patientName: "Liam Davis",
    time: "3:00 PM",
    endTime: "3:45 PM",
    date: "2026-08-27",
    treatment: "Implant maintenance",
    treatmentPrice: 420,
    doctor: "Dr. Sarah Kim",
    providerId: "demo-doctor-3",
    room: "Room 3",
    status: "Confirmed",
    color: "#0f9f8f",
  },
];

export const treatmentPlans: TreatmentPlan[] = [
  {
    id: "t1",
    patientId: "p1",
    patientName: "Sophia Martinez",
    title: "Upper-right restoration",
    procedures: ["Root canal", "Porcelain crown"],
    total: 2450,
    sessionsDone: 2,
    sessionsTotal: 4,
    progress: 50,
    status: "In progress",
    nextSession: "Sep 03",
  },
  {
    id: "t2",
    patientId: "p3",
    patientName: "Emma Thompson",
    title: "Clear aligner treatment",
    procedures: ["Digital scan", "18 aligner sets", "Retainers"],
    total: 4800,
    sessionsDone: 5,
    sessionsTotal: 9,
    progress: 56,
    status: "In progress",
    nextSession: "Sep 12",
  },
  {
    id: "t3",
    patientId: "p4",
    patientName: "Noah Williams",
    title: "Implant rehabilitation",
    procedures: ["Extraction", "Bone graft", "Implant", "Crown"],
    total: 6800,
    sessionsDone: 0,
    sessionsTotal: 6,
    progress: 0,
    status: "Proposed",
  },
  {
    id: "t4",
    patientId: "p2",
    patientName: "Marcus Chen",
    title: "Endodontic therapy",
    procedures: ["Root canal", "Core build-up"],
    total: 1850,
    sessionsDone: 2,
    sessionsTotal: 3,
    progress: 67,
    status: "In progress",
    nextSession: "Aug 28",
  },
  {
    id: "t5",
    patientId: "p5",
    patientName: "Olivia Brown",
    title: "Preventive care",
    procedures: ["Exam", "Cleaning", "Fluoride"],
    total: 320,
    sessionsDone: 1,
    sessionsTotal: 1,
    progress: 100,
    status: "Completed",
  },
];

export const payments: Payment[] = [
  {
    id: "pay1",
    invoice: "INV-1089",
    patientName: "Marcus Chen",
    treatment: "Root canal",
    originalPrice: 1850,
    date: "Aug 27, 2026",
    total: 1850,
    paid: 1850,
    discount: 0,
    method: "Card",
    status: "Paid",
  },
  {
    id: "pay2",
    invoice: "INV-1088",
    patientName: "Sophia Martinez",
    treatment: "Upper-right restoration",
    originalPrice: 2450,
    date: "Aug 26, 2026",
    total: 2450,
    paid: 2030,
    discount: 0,
    method: "Insurance",
    status: "Partial",
  },
  {
    id: "pay3",
    invoice: "INV-1087",
    patientName: "Olivia Brown",
    treatment: "Preventive care",
    originalPrice: 320,
    date: "Aug 24, 2026",
    total: 320,
    paid: 320,
    discount: 25,
    method: "Cash",
    status: "Paid",
  },
  {
    id: "pay4",
    invoice: "INV-1086",
    patientName: "Emma Thompson",
    treatment: "Clear aligner treatment",
    originalPrice: 4800,
    date: "Aug 22, 2026",
    total: 4800,
    paid: 3550,
    discount: 200,
    method: "Bank transfer",
    status: "Partial",
  },
  {
    id: "pay5",
    invoice: "INV-1085",
    patientName: "Noah Williams",
    treatment: "Implant rehabilitation",
    originalPrice: 1280,
    date: "Aug 18, 2026",
    total: 1280,
    paid: 500,
    discount: 0,
    method: "Card",
    status: "Overdue",
  },
];

export const procedureCatalog: ProcedureCatalogItem[] = [
  ["Filling", "Restorative", 50000], ["Bridge", "Restorative", 450000],
  ["Examination", "Diagnostic", 25000], ["Extraction", "Surgical", 75000],
  ["Cleaning", "Preventive", 50000], ["Root Canal", "Endodontic", 200000],
  ["Crown", "Restorative", 300000],
].map(([name, category, price], index) => ({
  id: `demo-procedure-${index}`, name: String(name), category: String(category),
  defaultPrice: Number(price), defaultSessions: name === "Root Canal" ? 2 : 1,
  supportsSurfaces: name === "Filling", supportsMultipleTeeth: name === "Bridge",
  isSystem: false, isActive: true,
}));

export const clinicMembers: ClinicMember[] = [
  { id: "demo-owner", userId: "demo-owner", fullName: "Dr. Maya Chen", email: "owner@brightsmile.test", role: "owner", status: "active", specialty: "Clinic administrator" },
  { id: "demo-doctor-1", userId: "demo-doctor-1", fullName: "Dr. Maya Chen", email: "maya@brightsmile.test", role: "dentist", status: "active", specialty: "General dentistry" },
  { id: "demo-doctor-2", userId: "demo-doctor-2", fullName: "Dr. James Wilson", email: "james@brightsmile.test", role: "dentist", status: "active", specialty: "Endodontics" },
  { id: "demo-doctor-3", userId: "demo-doctor-3", fullName: "Dr. Sarah Kim", email: "sarah@brightsmile.test", role: "dentist", status: "active", specialty: "Periodontics" },
  { id: "demo-staff-1", userId: "demo-staff-1", fullName: "Ava Robinson", email: "ava@brightsmile.test", role: "front_desk", status: "active", specialty: "Reception" },
];

export const inventoryItems: InventoryItem[] = [
  {
    id: "i1",
    name: "Nitrile gloves · M",
    category: "PPE",
    sku: "PPE-GLV-M",
    stock: 6,
    minimum: 12,
    unit: "boxes",
    supplier: "MedSupply Co.",
  },
  {
    id: "i2",
    name: "Composite resin A2",
    category: "Restorative",
    sku: "RST-CRA2",
    stock: 4,
    minimum: 5,
    unit: "syringes",
    supplier: "Henry Schein",
    expiry: "Mar 2027",
  },
  {
    id: "i3",
    name: "Articaine 4%",
    category: "Anaesthetic",
    sku: "ANE-ART4",
    stock: 18,
    minimum: 10,
    unit: "boxes",
    supplier: "Patterson Dental",
    expiry: "Nov 2027",
  },
  {
    id: "i4",
    name: "Sterilization pouches",
    category: "Sterilization",
    sku: "STR-PCH",
    stock: 22,
    minimum: 8,
    unit: "packs",
    supplier: "MedSupply Co.",
  },
  {
    id: "i5",
    name: "Implant fixture · 4.1",
    category: "Surgical",
    sku: "SUR-IMP41",
    stock: 2,
    minimum: 3,
    unit: "units",
    supplier: "Straumann",
  },
  {
    id: "i6",
    name: "Prophy paste · Mint",
    category: "Preventive",
    sku: "PRE-PPM",
    stock: 14,
    minimum: 6,
    unit: "boxes",
    supplier: "Patterson Dental",
  },
];

export const revenueData = [
  { month: "Mar", revenue: 29400, expenses: 16800 },
  { month: "Apr", revenue: 32600, expenses: 17900 },
  { month: "May", revenue: 31800, expenses: 17200 },
  { month: "Jun", revenue: 37400, expenses: 19100 },
  { month: "Jul", revenue: 39200, expenses: 20500 },
  { month: "Aug", revenue: 42680, expenses: 21400 },
];

export const staff = [
  {
    name: "Dr. Maya Chen",
    role: "Lead Dentist",
    specialty: "Restorative & Cosmetic",
    initials: "MC",
    color: "bg-teal-100 text-teal-700",
    status: "In clinic",
    patients: 8,
  },
  {
    name: "Dr. James Wilson",
    role: "Dentist",
    specialty: "Endodontics & Surgery",
    initials: "JW",
    color: "bg-violet-100 text-violet-700",
    status: "In clinic",
    patients: 6,
  },
  {
    name: "Dr. Sarah Kim",
    role: "Dentist",
    specialty: "Implantology",
    initials: "SK",
    color: "bg-blue-100 text-blue-700",
    status: "In clinic",
    patients: 5,
  },
  {
    name: "Ava Robinson",
    role: "Dental Hygienist",
    specialty: "Preventive care",
    initials: "AR",
    color: "bg-amber-100 text-amber-700",
    status: "With patient",
    patients: 7,
  },
  {
    name: "Ethan Moore",
    role: "Dental Assistant",
    specialty: "Clinical support",
    initials: "EM",
    color: "bg-rose-100 text-rose-700",
    status: "In clinic",
    patients: 0,
  },
  {
    name: "Mia Taylor",
    role: "Clinic Administrator",
    specialty: "Operations & billing",
    initials: "MT",
    color: "bg-cyan-100 text-cyan-700",
    status: "In clinic",
    patients: 0,
  },
];
